# fly.toml app configuration file generated for kippo-bot on 2023-09-20T22:53:15+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kippo-bot"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
